version: '3'
services:
    client:
        build: ./client-web
        ports:
            - "8888:8888"
        volumes:
            - ./client-web:/home/client
        command: npm run build # webpack bundle analyser not working ?
